CREATE TABLE IF NOT EXISTS user_tab (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS wallet_tab (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT NOT NULL REFERENCES user_tab(id),
    name               VARCHAR(128) NOT NULL,
    currency           VARCHAR(3) NOT NULL,
    available_balance  DECIMAL(19,4) NOT NULL DEFAULT 0,
    -- Unix timestamp in seconds, UTC.
    created_at         INT NOT NULL,
    updated_at         INT NOT NULL,
    CONSTRAINT chk_wallets_balance_non_negative CHECK (available_balance >= 0)
);

